### ISSUE TITLE
Accessing api endpoint from the browser

### ISSUE THREAD

**Issue by pulse00** [FriendsOfSymfony/FOSOAuthServerBundle#100]
We're working on a app where the API is used by a backbone.js client and native mobile clients. Right now our api endpoints can only be accessed through stateless firewall, when accessed by the browser by an authenticated user, we get `OAuth2 authentication required`.

However, we'd need to access the api endpoints from the browser as well, where the user is authenticated using cookie based authentication.

Is there a way to secure the API either by oauth2 or by the cookie authentication scheme? 

Currently our firewalls in `security.yml` look like this:

``` yaml
    firewalls:
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        webapp:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true


```
