### ISSUE TITLE
cant get the authentication process in the Oauth server

### ISSUE THREAD

**Issue by lizaaminov** [FriendsOfSymfony/FOSOAuthServerBundle#110]
hello,
I'm trying to create Oauth api server using FOSOauthServerBundle, FOSUserBundle and FOSRestBundle.
I followd the instructions on http://blog.logicexception.com/2012/04/securing-syfmony2-rest-service-wiith.html, and got the access token and the refresh token successfully. Now, I'm trying to test my server by creating a demo application that makes api requests. 
the result of the request is "access_denied, Oauth2 authentication required", in spite the fact the the user was authenticated and the client received an access token.
when i tried to debug the process i noticed that the oauth2 authentication process never executed.

my security.yml:
jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

```
role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

providers:
    in_memory:
        memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    fos_userbundle:
        id: fos_user.user_provider.username

encoders:
      FOS\UserBundle\Model\UserInterface: sha512
      Symfony\Component\Security\Core\User\User: plaintext

firewalls:
    api:
        pattern: ^/api
        fos_oauth: true
        stateless: true

    oauth_authorize:
        pattern: ^/oauth/v2/auth
        form_login:
            provider: fos_userbundle
            check_path: /oauth/v2/auth_login_check
            login_path: /oauth/v2/auth_login
            use_referer: true
        anonymous: true

    oauth_token:
        pattern: ^/oauth/v2/token
        security: false  

    secured_area:
        pattern:    ^/
        anonymous: ~
        form_login:
            provider: fos_userbundle
            check_path: /login_check
            login_path: /login
            always_use_default_target_path: true
            default_target_path: /

access_control:
    - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/oauth/v2/auth, role: ROLE_USER }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/, roles: ROLE_USER }
    - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```
