### ISSUE TITLE
Difference Beween IS_AUTHENTICATED_FULLY and IS_AUTHENTICATED_ANONYMOUSLY

### ISSUE THREAD

**Issue by jgiannuzzo** [FriendsOfSymfony/FOSOAuthServerBundle#133]
I have implemented FOSOauthServerBundle Authentication with FOSUserBundle and FOSRestApiBundle to obtain Rest Api with oauth authentication.
I have a client with grant_types password and client_credentials.
Now i need to manage two types of access to certain rest resources, anonymously and private. 
I tried to give different acces control in security.yml (IS_AUTHENTICATED_ANONYMOUSLY and IS_AUTHENTICATED_FULLY) but i can't undertand  when a given access token is considered "anonymous".

Here is my security.yml:

``` yaml
jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/api/v1/user, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```
