### ISSUE TITLE
Custom user provider not supported

### ISSUE THREAD

**Issue by pierrre** [FriendsOfSymfony/FOSOAuthServerBundle#135]
In DependencyInjection\Security\Factory\OAuthFactory, the custom provider config is not available.

I want to do this:

``` yaml
security:
    firewall:
        api:
            fos_oauth:
                provider: my_custom_provider

```

Is it a missing feature?
