### ISSUE TITLE
Set tokens to never expire

### ISSUE THREAD

**Issue by philippemiguet** [FriendsOfSymfony/FOSOAuthServerBundle#152]
Hi guys,

I was looking for a way to set the access token to never expire via the config.yml by passing the following config:

```
fos_oauth_server:
    service:
        options:
          # Changing tokens and authcode lifetime
            access_token_lifetime: false
            refresh_token_lifetime: false
            auth_code_lifetime: 30
```

But it doesn't work, it always feel the database with the current timestamp.

So I search in your code where the tokens are created and i found that you always pass in parameters:

```
OAuth2.php\createAccessToken(IOAuth2Client $client, $data, $scope=NULL)
time() + $this->getVariable(self::CONFIG_ACCESS_LIFETIME)
```

Is there a way to fix this and check is the config equals 0 or NULL or FALSE, to set the value to 0? If you explain me how, I can do the fix and push it on the branch.

Cheers!
