### ISSUE TITLE
Do "scopes" really are supported ?

### ISSUE THREAD

**Issue by benjamindulau** [FriendsOfSymfony/FOSOAuthServerBundle#161]
Hi,

I'm trying to use scope as described in the documentation.
But when trying to get an access token I always get a "An unsupported scope was requested." error.

Here is my configuration:

``` YML
fos_oauth_server:
    # ....
    service:
        options:
            supported_scopes: api_client
```

And the request information:

```
POST /oauth/v2/token HTTP/1.1
Host: xxxxx.local
Accept: application/json
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=1_fjo5spee054w0g8sookskgscog0g4w4gwcg8oswsgg44gwkcg&client_secret=40tgd6qo712cksoww48wc8cwsooowwg4g0wk0skko04sw04gg&scope=api_client
```

Request & config seem okay to me. Am I missing something important ?

Note that without any scope, the auth workflow works without any problem.

Thanks.
