### ISSUE TITLE
Response is not a valid JSON code.

### ISSUE THREAD

**Issue by AliceMakk** [FriendsOfSymfony/FOSOAuthServerBundle#165]
Hello all!

I have 2 servers:
First: Install FOSOAuthServerBundle + FOSRestBundle + FOSUserBundle
Second: Install HWIOAuthBundle + FOSUserBundle

When i try to call my first server like http://mysecondsite.com/login/my_custom i'm redirect to http://myfirstsite.com/login where i authorized, then when i click "Allow" i redirect to http://mysecondsite.com and i see error "Response is not a valid JSON code."

This my config.yml on First server:

``` yaml
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: false
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

sensio_framework_extra:
    view:
        annotations: false

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUserBundle""
```

What am I doing wrong?
Thanks.
Sorry about my english.
