### ISSUE TITLE
can't authenticate using FOSUserBundle

### ISSUE THREAD

**Issue by echoedexistence** [FriendsOfSymfony/FOSOAuthServerBundle#174]
I've had the following in my config.yml:

```
  oauth_authorize:
            pattern: ^/oauth/v2/auth 
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true
```

however when ever I try to login to:

http://local.acme/oauth/v2/auth?client_id=3_5ph2tuyxay048ksksgko4ocs4ss8kssws8k8osgk8o08go0goc&response_type=code&redirect_uri=http%3A%2F%2Fwww.google.com

it doesn't prompt me/redirect me to the /oauth/v2/auth_login first instead it directly asks me for permission to grant to the client. What am I possibly doing wrong?
