### ISSUE TITLE
Problem With  Token Refresh

### ISSUE THREAD

**Issue by emgiezet** [FriendsOfSymfony/FOSOAuthServerBundle#176]
Howdy Mates!

I'm integrating mobile app with my symfony2 project and I choose the FOSOAuthServerBundle to secure my Rest api. Under influence of logicexception.

I found little thing. Refreshing token wont work.

I checked in the oAuth2-php soruce and found this: https://github.com/FriendsOfSymfony/oauth2-php/blob/master/tests/OAuth2Test.php#L485

**The compleate flow**:
1. I'm authenticating:

```
oauth/v2/token?grant_type=password&username=test_user1&password=test&client_id=1_randomIdHere&client_secret=clientSecretHere
```
1. Result:
   
   ``` json
   {
       "access_token": "YmZmYjExMWYxYzc4YTBlZjVhZjEyZjU4YzI0YzlhODZmZDM3ZWIwMjY5MTNjZGIxNWQ2MTFjYjQyNDcxZDAwZQ",
       "expires_in": 3600,
       "token_type": "bearer",
       "scope": null,
       "refresh_token": "NTc0MWJhZDJlNzJiNGIwYjJlNjFkYWUyOTI3NjJhN2JkNWE0MGI1YTFiOGI1MDJiZDIyZGQ2MTM0YWM5MDE4Ng"
   }
   ```
   
   I can retrive data from the API. All Good!
2. Refresh Request
   
   ```
       /oauth/v2/token?grant_type=refresh_token&client_id=1_randomId&client_secret=clientSecretHere&refresh_token=NTc0MWJhZDJlNzJiNGIwYjJlNjFkYWUyOTI3NjJhN2JkNWE0MGI1YTFiOGI1MDJiZDIyZGQ2MTM0YWM5MDE4Ng
   ```
3. Result of token refresh:
   
   ``` json
   {
       "error": "unauthorized_client",
       "error_description": "The grant type is unauthorized for this client_id"
   }
   ```

When I saw the description I checked mine client config in fixtures:

``` yaml
    director:
        id: 1
        name: app1
        random_id: randomId
        secret: SecretHere
        allowedGrantTypes: ['refresh_token', 'token', 'password']
        redirectUris: ['http://www.google.com']
```

DB? there's `refresh_token` in the serialized array in the allowed_grant_types field.

Something is wrong. Russian debug school with `var_dump()` and `die()` didn't help.

There is sth with: https://github.com/FriendsOfSymfony/oauth2-php/blob/master/lib/OAuth2/OAuth2.php#L690

Maybe some data isn't passed to the oAuthServer? 

Any help will be glorious! 
Max
