### ISSUE TITLE
Problem to access the API route after auth

### ISSUE THREAD

**Issue by createproblem** [FriendsOfSymfony/FOSOAuthServerBundle#177]
Hello.

I worked a very long time to get this bundle work... impossible for me....

My problem is I can't access my `^api/` route. If I access these route I get a forward to my login page.

For my user management I'll use FOSUserBundle. Its configured correctly and works.
For Custom user providers I'm using HWIOAuthBundle. Its works great with FOSUserBundle.

Now. I need an OAuth 2.0 Server to protect my API.
## Workflow OAuth
1. At the first step the client goes to the auth endpoint, `/oauth/v2/auth` I get a forward to my login page (/login), so I can enter my credentials.
2. Next I've to allow the client application to access. `/oauth/v2/auth?approval_prompt=force&client_id=8_someid&redirect_uri=http%3A%2F%2Fexample.com&response_type=code&scope=scope1&state=64ab7`
3. If I press Allow I get a redirect to my client application. `example.com?state=64&code=ZTw`
4. Now I will call my API `/api/me?access_token=ZTw`. This call will me redirect to my login page `/login`.

Can someone tell me please whats going on? I attached my configurations. I've no idea where to look for the error.
## security.yml

``` yml
firewalls:
    main:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
            login_path: /login
            check_path: /login_check

        oauth:
            resource_owners:
                facebook: "/login/check-facebook"
            login_path: /login
            failure_path: /login
            oauth_user_provider:
                service: my_user_provider

        logout:       true
        anonymous:    true

    oauth_token:
        pattern: ^/oauth/v2/token
        security: false

    oauth_authorize:
        pattern: ^/oauth/v2/auth
        form_login:
            provider: fos_userbundle
            login_path: /login
            check_path: /login_check
        anonymous: true

    api:
        pattern: ^/api
        fos_oauth: true
        stateless: true

    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```
## config.yml

``` yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: ggm\UserBundle\Entity\User
    registration:
        form:
            type: ggm_user_registration

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        ggm\ApiBundle\Entity\Client
    access_token_class:  ggm\ApiBundle\Entity\AccessToken
    refresh_token_class: ggm\ApiBundle\Entity\RefreshToken
    auth_code_class:     ggm\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            supported_scopes: scope1
            enforce_state: true
```

Thanks for help.
