### ISSUE TITLE
Difficulty to implement the bundle

### ISSUE THREAD

**Issue by manonthemoon42** [FriendsOfSymfony/FOSOAuthServerBundle#212]
Hi,

My app works well, i'm using FOSUserBundle to manage users. 
I wanted to implement FOSOAuthServerBundle, to add more security for my API... 
I met some issues... I followed all instructions on documentation for installing the bundle. 

Here my security.yml before implementing FOSOAuthServerBundle :

```
firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false
    main:
        pattern: ^/
        anonymous: true
        provider: main
        form_login:
            default_target_path: /
            always_use_default_target_path: true
            login_path: fos_user_security_login
            check_path: fos_user_security_check
        logout:
            path: fos_user_security_logout
            target: /
        remember_me:
            key: %secret%
access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```

Before, when I went to my index page, it worked very well, I could register, login etc... 
I changed security.yml by following instruction in documentation : 

This is my new security.yml  : 

```
firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false
    oauth_token:
        pattern:    ^/oauth/v2/token
        security:   false
    oauth_authorize:
        pattern:    ^/oauth/v2/auth
        form_login:
            provider: main
            check_path: /oauth/v2/auth_login_check
            login_path: /oauth/v2/auth_login
        anonymous: true
    api:
        pattern: ^/api
        fos_oauth: true
        stateless:  true

access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
     - { path: ^/api/user/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/oauth/v2/auth_login, role: IS_AUTHENTICATED_ANONYMOUSLY }
```

in config.yml :

```
fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        Moodress\Bundle\OAuthBundle\Entity\Client
    access_token_class:  Moodress\Bundle\OAuthBundle\Entity\AccessToken
    refresh_token_class: Moodress\Bundle\OAuthBundle\Entity\RefreshToken
    auth_code_class:     Moodress\Bundle\OAuthBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
```

With this configuration I can't do anything. My page doesn't work... 
When I go to route / (index...) . I have this exception :

![capture decran 2014-02-10 a 11 59 50](https://f.cloud.github.com/assets/2165625/2129957/b4f0ca94-928d-11e3-8822-d12afc4985e1.png)

I'm not sure how I have to configure well my files :/ ... 

Then, In documentation, there is code for creating a client... Should I create a custom confirmed route after authentification ? I mean... I'm supposed to create a new client, if the authentification was success right? If It was success, I should create a client with token I guess... What is the file recommended to implement creating client ? 

I'm sorry with all this questions, I really try to make it works, but could't find any other solutions. Help please
