### ISSUE TITLE
Password grant_type auth users by email address

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSOAuthServerBundle#215]
Hey guys, 

I'm using the "password" grant_type of the FOSOAuthServerBundle. Everything works as expected, I send a UsernamePasswordToken to my token endpoint and can retrieve an access/refresh token. The problem is, that I want to auth users by their email address and not by their username. If I do so the bundle responses with a { "error" : "invalid_grant" }. Seems that the bundle looks at the username_canonical field. Is it possible to change this behavior?

Security.yml:

``` yml
security:
    encoders:
        Foo\BarBundle\Model\Acl\Customer\Customer: plaintext
    providers:
        main:
            propel:
                class: Foo\BarBundle\Model\Acl\Customer\Customer
                property: email
    firewalls:
        basic:
            pattern:   ^/docs
            http_basic:
                realm: "Foo API Documentation"
        oauth:
            pattern:   ^/security/oauth/token
            security:  false
        api:
            pattern   : ^/
            fos_oauth : true
            stateless : true
            anonymous : true
```

The email provider property works as expected for http basic auth, but not for oauth.
