### ISSUE TITLE
No route find for oauth/v2/auth_login

### ISSUE THREAD

**Issue by maxtor3569** [FriendsOfSymfony/FOSOAuthServerBundle#257]
Hello everybody !

I'm trying to implement FOSOAuthServerBundle for my IOS app

When I try to access to /oauth/v2/auth_login no route found...

I define my route in app/config/routing.yml like this : 

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

This route already works : 
 /oauth/v2/auth
it's redirect me on my login page..
My security.yml

```yaml
 oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
            
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
              provider: fos_userbundle
              check_path: /oauth/v2/auth_login_check
              login_path: /oauth/v2/auth_login
            anonymous: true
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
   main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                default_target_path: /
                failure_path:   null
            logout:       true
            anonymous:    true
```

Also other question because I'm lost.. : Should I create a client after the user has logging in in the fosuserbundle form? 

Thanks a lot !!
