### ISSUE TITLE
Gran Extension not working

### ISSUE THREAD

**Issue by compains** [FriendsOfSymfony/FOSOAuthServerBundle#299]
I have prepared a class for custom grant procedure that looks like

````
<?php


namespace AppBundle\OAuth;

use FOS\OAuthServerBundle\Storage\GrantExtensionInterface;
use OAuth2\Model\IOAuth2Client;
use Symfony\Component\DependencyInjection\Container;

/**
 * Class SocialGrantExtension
 * @package AppBundle\OAuth
 */
class SocialGrantExtension implements GrantExtensionInterface{

    /**
     * @var Container
     */
    private $serviceContainer;

    /**
     * @param Container $userRepository
     */
    public function __construct(Container $serviceContainer)
    {
        $this->serviceContainer = $serviceContainer;
    }

    /*
     * {@inheritdoc}
     */
    public function checkGrantExtension(IOAuth2Client $client, array $inputData, array $authHeaders)
    {
        /// look for user do some checks an  return it.
    }

}
```

then I configure the extension like:

```
oauth.social_oauth_grant:
        class: AppBundle\OAuth\SocialGrantExtension
        arguments: [@service_container]
        tags:
            - { name: fos_oauth_server.grant_extension, uri: "http://somehost.net/custom_grant" }

```

I have done some debug job and I'm pretty sure that:

- The service is initialized on the compiler pass. I have dumped it while executing cache:clear
- The  extensión is not available at the OAuthStorageClass when checkGrantExtension is called because grantExtensions array is empty.

I make some calls to get the access_token with other grant types and they work properly but if y use this grant type i get:

![image](https://cloud.githubusercontent.com/assets/8570898/6652102/ef4c5cae-ca62-11e4-9e95-8bed1ee13255.png)

¿Any advise?

By the way I'm not sure if this is the right place (if this is an issue), if not, sorry for the confusion and feel free to move it to the right place.
