### ISSUE TITLE
Missing "error_uri" parameter error response

### ISSUE THREAD

**Issue by ktounet** [FriendsOfSymfony/FOSOAuthServerBundle#305]
Hi,

Need to set the optional parameter "error_uri" as described in RFC (http://tools.ietf.org/html/rfc6749#section-5.2).
But this isn't supported by FOSOAuthServerBundle and oauth2-php lib. I should make a PR ?

Thanks.

**Comment by Spomky** [comment]
You could intercept the response using a listener and add this parameter :

```yml
services:
  my.interceptor:
    class: My\AwesomeBundle\Listener\MyInterceptor
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
```

```php
namespace My\AwesomeBundle\Listener;

use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;

class MyInterceptor
{
    public function onKernelResponse(FilterResponseEvent $event)
    {
        $response  = $event->getResponse();
        
        //Do the magic here
        return $response;
    }
}
```
