### ISSUE TITLE
Firewall some route in whitelist

### ISSUE THREAD

**Issue by Giuffre** [FriendsOfSymfony/FOSOAuthServerBundle#318]
I have firewall configuration like this:
```yaml
security:
    acl:
        connection: default
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true

        api:
            pattern:    ^/.*
            fos_oauth:  true
            stateless:  true
            anonymous: false

    access_control:
        - { path: ^/, methods: [GET], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: ^/doc, methods: [GET], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: ^/resque, methods: [GET], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: /monitor, methods: [GET], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: /users, methods: [POST], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: /users/me/registration/confirm, methods: [GET], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: /users/me/email/confirm, methods: [GET], roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: /instants/.*, methods: [PUT], roles: [IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: ^/_profiler, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/_wdt, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/_configurator, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: /.*, roles: [ IS_AUTHENTICATED_FULLY ]}
```
But the routes `/resque`, `/monitor` and others are not reachable without access token.
Am I doing something wrong in the configuration? Or is not possible to implement a route whitelist?
