### ISSUE TITLE
How to get protected resource with access_token?

### ISSUE THREAD

**Issue by edamov** [FriendsOfSymfony/FOSOAuthServerBundle#329]
I am trying to configure bundle and I have one problem.

I created a client and got user token by url:
```
/oauth/v2/token?client_id=CLIENT_ID&client_secret=CLIENT_SECRET&grant_type=password&username=USERNAME&password=PASS
```

But I can't get any protected resources with this token:
```
/api/products?access_token=ACCESS_TOKEN  
```
I always get the same error "Full authentication is required to access this resource."

``` yaml
# security.yml
security:
    encoders:
        DemoBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        user_provider:
            id: provider.user

    firewalls:
        oauth_token:
             pattern:    ^/oauth/v2/token
             security:   false

        oauth_authorize:
             pattern:    ^/oauth/v2/auth
             anonymous: true

        api:
              pattern:    ^/api
              fos_oauth:  true
              stateless:  true
              anonymous:  false 
              provider: user_provider

    access_control:
       - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```

Can you help me with this problem?
