### ISSUE TITLE
[QUESTION] Is there away to change the access token generation URL

### ISSUE THREAD

**Issue by samgavinio** [FriendsOfSymfony/FOSOAuthServerBundle#340]
Attempting to change `oauth/v2/token` to `api/v1/login`.

May be I just missed it from the docs but haven't found a way to do this yet without changing `FOSOAuthServerBundle/Resources/config/routing/token.xml` directly.

My attempt at this by using the routing file of my own bundle:
```
# app/config/routing.yml
fos_oauth_server_token:
    resource: "@MyOwnAppBundle/Resources/config/routing/token.xml"
```

```
# app/config/security.yml
security:
    firewalls:
        oauth_token:
            pattern:    ^/api/v1/login
            security:   false
```

```
#MyOwnAppBundle/Resources/config/routing/token.xml
oauth_token_generation:
    path: /api/v1/login
    defaults: { _controller: FOSOAuthServerBundle:Token:token }
    methods: [GET]
```

This is what I get:
```
Catchable Fatal Error: Argument 1 passed to FOS\OAuthServerBundle\Controller\TokenController::__construct() must be an instance of OAuth2\OAuth2, none given
```

Most likely because the `TokenController` is declared as a service.
