### ISSUE TITLE
grant_type "password" not working

### ISSUE THREAD

**Issue by BirknerAlex** [FriendsOfSymfony/FOSOAuthServerBundle#352]
Hello,

I think I got nearly the same issue like discussed in #261. I'm using this Symfony2 project only as oAuth2 Server. No other routes are available. The web login flow via /oauth/v2/auth uri is working fine. Only the grant_type password flow seems to throw a error in OAuthStorage.php in line 161:

$this->userProvider is null instead of a UserProvider instance.
```php
        try {
            $user = $this->userProvider->loadUserByUsername($username);
        } catch (AuthenticationException $e) {
            return false;
        }
```

This is my full security.yml:
```yml
security:
    encoders:
        Marbis\oAuthBundle\Entity\User:
            id: nitrado.password.encoder

    providers:
        #user_provider:
        #    id: platform.user.provider
        user_provider:
            entity: { class: MarbisoAuthBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                check_path: login_check
                login_path: login
            anonymous: true
``` 

And last but not least my config.yml:
```yml
fos_oauth_server:
    db_driver: orm
    client_class: Marbis\oAuthBundle\Entity\Client
    access_token_class: Marbis\oAuthBundle\Entity\AccessToken
    refresh_token_class: Marbis\oAuthBundle\Entity\RefreshToken
    auth_code_class: Marbis\oAuthBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider
        options:
            access_token_lifetime: 2592000
            refresh_token_lifetime: 7776000
            supported_scopes: user_info service service_order admin_databases admin_server_access admin_server_credentials admin_license_keys admin_callbacks admin_customer_sudo
```

Have I missed something? 

Best regards
Alexander Birkner
