### ISSUE TITLE
Login Redirects Not Working As Expected

### ISSUE THREAD

**Issue by zquintana** [FriendsOfSymfony/FOSOAuthServerBundle#382]
First off, great bundle. Works well out of the box for many things. Recently I noticed an oddity while using the bundle for authorization for third-party apps. We're trying to authenticate logins from other entities using oauth style logins. I realize this should work by setting the oauth_authorize firewall up in the security config. That's setup but here is the issue when that is configured before our main firewall setup the login urls redirects for oauth login work as desired, but the user token is always anonymous. However when I move the configuration after the main firewall, the redirects for the oauth login don't work as desired, but the user token is populated appropriately. What am I missing here?

Example of working user token, but failing login redirect. This results in login redirect pointing to the `main` firewall login:

``` yaml
# excerpt from security.yml
security:
    # ... providers, encoders 
    firewalls:
        api:
            pattern:    ^/api/v1
            fos_oauth:  true
            stateless:  true
            anonymous:  false 

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        main:
            provider: user_provider
            anonymous: ~
            remember_me:
                key:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            simple_form:
                authenticator: app_authenticator
                check_path:    login_check
                login_path:    login

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            simple_form:
                authenticator: app_authenticator
                check_path: oauth_login_check
                login_path: oauth_login
            anonymous: true
```

Example of anonymous user token, but working oauth login redirect. This results in login redirect pointing to the `oauth_authorize` firewall login, but with an anonymous user token:

``` yaml
# excerpt from security.yml
security:
    # ... providers, encoders 
    firewalls:
        api:
            pattern:    ^/api/v1
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            simple_form:
                authenticator: app_authenticator
                check_path: oauth_login_check
                login_path: oauth_login
            anonymous: true

        main:
            provider: user_provider
            anonymous: ~
            remember_me:
                key:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            simple_form:
                authenticator: app_authenticator
                check_path:    login_check
                login_path:    login
```
