### ISSUE TITLE
Authenticate API by oAuth or Normal

### ISSUE THREAD

**Issue by iBasit** [FriendsOfSymfony/FOSOAuthServerBundle#384]
Hi,

I want to fetch url information about user, if user has logged in from normal website login, which is without oauth.

I'm not sure what I have to do on my security settings to have that accomplish.

btw I dont want to give anonymous access, it is only access to login user via oAuth or logged in on the site using user_firewall security.

```yml
firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            provider: user
            form_login:
                check_path: oauth_login_check
                login_path: oauth_login
                csrf_provider: security.csrf.token_manager
                username_parameter: _email
                csrf_parameter: secure
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        user_firewall:
            pattern: ^/
            anonymous: ~
            provider: user
            oauth:
                resource_owners:
                    facebook:      "/login/check-facebook"
                login_path:        login
                use_forward:       false
                failure_path:      login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

            form_login:
                check_path: login_check
                login_path: login
                csrf_provider: security.csrf.token_manager
                default_target_path: home
                username_parameter: _email
                csrf_parameter: secure
            remember_me:
                key:   "%secret%"
            logout:
                path:   logout
                target: home


    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```
