### ISSUE TITLE
Could not load type "fos_oauth_server_authorize"

### ISSUE THREAD

**Issue by psampaz** [FriendsOfSymfony/FOSOAuthServerBundle#386]
While trying to access fos_oauth_server_authorize (oauth/v2/auth) route

I get the following error:

Could not load type "fos_oauth_server_authorize"

This is my config
```
# app/config/config.yml

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        OAuth2ServerBundle\Entity\Client
    access_token_class:  OAuth2ServerBundle\Entity\AccessToken
    refresh_token_class: OAuth2ServerBundle\Entity\RefreshToken
    auth_code_class:     OAuth2ServerBundle\Entity\AuthCode
```

This is the output from "php bin/console debug:config fos_oauth_server"
```
Current configuration for extension with alias "fos_oauth_server"
=================================================================

fos_oauth_server:
    db_driver: orm
    client_class: OAuth2ServerBundle\Entity\Client
    access_token_class: OAuth2ServerBundle\Entity\AccessToken
    refresh_token_class: OAuth2ServerBundle\Entity\RefreshToken
    auth_code_class: OAuth2ServerBundle\Entity\AuthCode
    model_manager_name: null
    authorize:
        form: { type: fos_oauth_server_authorize, handler: fos_oauth_server.authorize.form.handler.default, name: fos_oauth_server_authorize_form, validation_groups: [Authorize, Default] }
    service:
        storage: fos_oauth_server.storage.default
        user_provider: null
        client_manager: fos_oauth_server.client_manager.default
        access_token_manager: fos_oauth_server.access_token_manager.default
        refresh_token_manager: fos_oauth_server.refresh_token_manager.default
        auth_code_manager: fos_oauth_server.auth_code_manager.default
        options: {  }
    template:
        engine: twig

```

Any ideas what could go wrong?
