### ISSUE TITLE
Heeeelp ! No mapping file found named 'Client.orm.xml' 

### ISSUE THREAD

**Issue by pierred69** [FriendsOfSymfony/FOSOAuthServerBundle#444]
Hi there,

I would need some help. I try to set up FOSOAuthServerBundle in my rest API, but I'm locked by a problem. I added the client entity extending the FOS\OAuthServerBundle\Entity\Client

```
<?php
// src/Acme/ApiBundle/Entity/Client.php

namespace AppBundle\Entity;

use FOS\OAuthServerBundle\Entity\Client as BaseClient;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Client extends BaseClient
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }
}
```

I also correctly configured my API in my config.yml : 

```
fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode
service:
    user_provider: fos_user.user.username
```

I configured my firewall : 

```
firewalls:
        api:
            pattern:    ^/api/v1
            fos_oauth:  true
            stateless:  true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
```

And of course my router.

```
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

```

All my tables in my database have their entity class and xml entity, but for the four classes to configure for FOSOAuthServerBundle, I don't have any xml, so I get this error.

Do I have to create an XML file for each classes ? Or what do I have to do ?

Thanks.
