### ISSUE TITLE
The Token access is not detected by Symfony but it is in the HTTP header

### ISSUE THREAD

**Issue by ThomAille** [FriendsOfSymfony/FOSOAuthServerBundle#474]
Hi All, 

I have set up an API which is protected in Oauth thanks to this bundle.
On another application I installed HwioauthBundle to make my authentication to my API
I get my access_token on my application. 
However, when I retrieve the user information, my API tells me that I am not authenticated

I corrected the first error which was that apache rewrite the http header
In my Symfony profile I have in the http header a token Authorization

![capture du 2017-07-26 15-22-50](https://user-images.githubusercontent.com/3932739/28623473-5c6b300a-7216-11e7-9a27-9d62865ad049.png)

I block. I can not understand why he does not want to connect my user.

Symfony version : 2.7.31
FOSOauthServerBundle : dev-master
HWIOauthBundle : 0.5.3

app/config/config.yml
```yaml
fos_oauth_server:
    db_driver: orm
    client_class:        Toto\Bundle\AppBundle\Entity\Client
    access_token_class:  Toto\Bundle\AppBundle\Entity\AccessToken
    refresh_token_class: Toto\Bundle\AppBundle\Entity\RefreshToken
    auth_code_class:     Toto\Bundle\AppBundle\Entity\AuthCode
    service:
        user_provider: toto_oauth.user_provider
        options:
          supported_scopes: user
    model_manager_name:  toto
```
app/config/security.yml
```yaml
security:
    providers:
        chain_provider:
            chain :
                providers: [oauth]
        oauth:
            entity: {class: Toto\Bundle\AppBundle\Entity\User, property: username, manager_name: toto}

    encoders:
        Toto\Bundle\AppBundle\Entity\User:
            id: toto_oauth.password.encoder
        Symfony\Component\Security\Core\User\User:
            algorithm:  sha512
            iterations: 1
            encode_as_base64: false

    firewalls:
        dev:
            pattern:      ^/(_(profiler|wdt)|css|images|js)/
            security:     false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: oauth
                check_path: /oauth/v2/auth/login_check
                login_path: /oauth/v2/auth/login

            anonymous: true

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false

    access_control:
        - { path: ^/_fos_user_context_hash, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/api, role: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

Thank you in advance for your help

Best Regards 
Thomas
