### ISSUE TITLE
Error requiring bundle from composer on SF4

### ISSUE THREAD

**Issue by SebScoFr** [FriendsOfSymfony/FOSOAuthServerBundle#501]
Command: `composer require friendsofsymfony/oauth-server-bundle:dev-master`

Fails with

```Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 238:
!!
!!    The child node "db_driver" at path "fos_oauth_server" must be configured.
!!
!!
!!

**Comment by dkarlovi** [comment]
There needs to exist a Flex recipe for the package for it to be auto-configured.

**Comment by SebScoFr** [comment]
Yes that is what I meant, I think a Flex recipe should be submitted to https://github.com/symfony/recipes at some point, but this is not a blocker, maybe a bit confusing for people new to Flex :)

**Comment by Luitame** [comment]
@SebScoFr how can you solved this problem?

`Executing script cache:clear [KO]`
`[KO]`
`Script cache:clear returned with error code 1`

` In ArrayNode.php line 238:`

    `The child node "db_driver" at path "fos_oauth_server" must be configured.`

**Comment by SebScoFr** [comment]
@Luitame 
If you are using SF4, make sure your **fos_auth_server.yaml** looks something like this (note the *db_driver* section):
```yml
fos_oauth_server:
    db_driver: mongodb
    client_class: App\Document\Client
    access_token_class: App\Document\AccessToken
    refresh_token_class: App\Document\RefreshToken
    auth_code_class: App\Document\AuthCode
    service:
        user_provider: App\Provider\UserProvider
```
If you're still on 3.x that will be within the *app/config.yml* file under the FOS configuration section
