### ISSUE TITLE
Not configuring explicitly the provider for the "fos_oauth" listener on "api" firewall is ambiguous as there is more than one registered provider

### ISSUE THREAD

**Issue by ibogdan94** [FriendsOfSymfony/FOSOAuthServerBundle#545]
Hi there
Faced with this exception: 

> InvalidConfigurationException
> Not configuring explicitly the provider for the "fos_oauth" listener on "api" firewall is ambiguous as there is more than one registered provider.
> 
> in SecurityExtension.php (line 415)

```yml
    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api:
            pattern: ^/api/v1/
            fos_oauth: true
            stateless: true
            anonymous: false
```
Symfony dependencies:
```json
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "^1.0",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "^4.0",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/validator": "^4.0",
        "symfony/web-profiler-bundle": "^4.0",
        "symfony/yaml": "^4.0"
```

friendsofsymfony/oauth-server-bundle from compose.lock

```json
{
            "name": "friendsofsymfony/oauth-server-bundle",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/FriendsOfSymfony/FOSOAuthServerBundle.git",
                "reference": "07f64710664f6d135902c93542bf0a35c5159bf9"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/FriendsOfSymfony/FOSOAuthServerBundle/zipball/07f64710664f6d135902c93542bf0a35c5159bf9",
                "reference": "07f64710664f6d135902c93542bf0a35c5159bf9",
                "shasum": ""
            },
            "require": {
                "friendsofsymfony/oauth2-php": "~1.1",
                "php": "^7.1",
                "symfony/dependency-injection": "~3.0|~4.0",
                "symfony/framework-bundle": "~3.0|~4.0",
                "symfony/security-bundle": "~3.0|~4.0"
            },
            "require-dev": {
                "doctrine/doctrine-bundle": "~1.0",
                "doctrine/mongodb-odm": "~1.0",
                "doctrine/orm": "~2.2",
                "phing/phing": "~2.4",
                "php-mock/php-mock-phpunit": "~1.0|~2.0",
                "phpstan/phpstan-phpunit": "~0.9",
                "phpstan/phpstan-shim": "~0.9",
                "phpunit/phpunit": "~5.0|~6.0",
                "propel/propel1": "~1.6",
                "symfony/class-loader": "~3.0|~4.0",
                "symfony/console": "~3.0|~4.0",
                "symfony/form": "~3.0|~4.0",
                "symfony/phpunit-bridge": "~3.0|~4.0",
                "symfony/templating": "~3.0|~4.0",
                "symfony/yaml": "~3.0|~4.0",
                "willdurand/propel-typehintable-behavior": "~1.0"
            },
            "suggest": {
                "doctrine/doctrine-bundle": "*",
                "doctrine/mongodb-odm-bundle": "*",
                "propel/propel-bundle": "If you want to use Propel with Symfony2, then you will have to install the PropelBundle",
                "symfony/console": "Needed to be able to use commands",
                "symfony/form": "Needed to be able to use the AuthorizeFormType",
                "willdurand/propel-typehintable-behavior": "The Typehintable behavior is useful to add type hints on generated methods, to be compliant with interfaces"
            },
            "type": "symfony-bundle",
            "extra": {
                "branch-alias": {
                    "dev-master": "2.0-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "FOS\\OAuthServerBundle\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Arnaud Le Blanc",
                    "email": "arnaud.lb@gmail.com"
                },
                {
                    "name": "FriendsOfSymfony Community",
                    "homepage": "https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/contributors"
                }
            ],
            "description": "Symfony2 OAuth Server Bundle",
            "homepage": "http://friendsofsymfony.github.com",
            "keywords": [
                "oauth",
                "oauth2",
                "server"
            ],
            "time": "2018-02-07T07:23:36+00:00"
        },
```
What I did wrong?
