### ISSUE TITLE
AUTHENTICATION_SUCCESS triggered too late

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSOAuthServerBundle#546]
I'm adding an ability for my user to have dynamic roles depending on which client the token belongs to. For this to work, I inject the current client and using it, fetch all the roles (sidenote, this allows me to have roles on the client too, for example I'm able to restrict access to certain parts of my API by using:

```yaml
security:
    access_control:
        # client roles, used to control access to modules, per-client
        - { path: ^/api/articles, roles: [ROLE_CLIENT_MODULE_ARTICLES] }
        - { path: ^/api/images, roles: [ROLE_CLIENT_MODULE_IMAGES] }

        # user roles
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```

Sadly, [OAuthProvider calls `User::getRoles()` **before** AUTHENTICATION_SUCCESS is dispatched](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Security/Authentication/Provider/OAuthProvider.php#L99). This means I'm unable to inject the client and my client-specific roles are not there when `access_control` is evaluated.

OAuthProvider seems very messy, we should clean it up.
