### ISSUE TITLE
[Symfony 4] Installation

### ISSUE THREAD

**Issue by er1z** [FriendsOfSymfony/FOSOAuthServerBundle#578]
Are there any docs covering installation on Symfony 4? I haven't found a recipe for Flex, should I be aware of any caveats?

**Comment by leroy0211** [comment]
I'm running on Symfony 4 (traditional, not flex).

Things I needed to configure were the `templating` section in `framework.yml` (also install the templating component). And a minor `security.yml` edit to allow multi route pattern firewalls. Because otherwise you have 2 login forms on your website. 

**templating section**
```
framework:
     # ... your config
     templating:
        hinclude_default_template:  ~
        form:
            resources:
                - FrameworkBundle:Form
        cache:                ~
        engines:
            - twig
        loaders:              []
```

**`security.yml` firewall edit**

```
# ...
firewalls:
      api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false

        main:
            pattern: ^/
            form_login:
                check_path: login  # name to check_path route
                login_path: login    # name to login_path route
            logout: true
            anonymous: true

        oauth_authorize:
            pattern: ^/oauth/v2/auth|^/login*   # this does the magic. Just use a regex to have multi-route-firewalls
            form_login: ~
            anonymous: true

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

```
