### ISSUE TITLE
Similar/same question as before. How to setup yaml without FOSUserBundle?

### ISSUE THREAD

**Issue by DPerkunas** [FriendsOfSymfony/FOSOAuthServerBundle#594]
Similar/same as this https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/467, just need more clarification.

the main question at hand is **oauth_authorize** setup. What should the authentication process look like? I tried using my handler from main via form_login : login_path , etc, but it says it does not follow the ^oauth/v2/ pattern. 

I'm able to create clients and on command shell. I can make calls to /oauth/v2/token and get access_tokens. I can't do anything on /oauth/v2/auth though. 

I'm trying to replicate the facebook style "{{ party }} is trying to gain access to photos, etc. Do you permit?"

thank you.

My Security.yaml
```
security:

    providers:
        my_users:
                    entity:
                        class:              App\Entity\Users

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_login:
            pattern: '^/oauth/v2/auth_login$'
            security: false

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false
            provider: my_users

        oauth_authorize:
            pattern: ^/oauth/v2/auth
            #guard:
            #    authenticators:
            #      - App\Security\ITHINKINEEDTHISFILE..
            ## Add your favorite authentication process here
            ## WHAT DOES THIS FILE CONTAIN/HANDLE?

        api:
            pattern:  ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        main:
            anonymous: ~
            form_login:
                            login_path: /login
                            check_path: /login
                            success_handler: App\Security\AuthenticationSuccessHandler

            provider: my_users

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ ROLE_AAA ] }
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth, role: ROLE_USER }
```
