### ISSUE TITLE
Extend OAuthStorage with LDAP

### ISSUE THREAD

**Issue by kapcus** [FriendsOfSymfony/FOSOAuthServerBundle#604]
Hi,

I would need to extend **OAuthStorage checkUserCredentials** method with a lookup into LDAP 

original code:
```
    public function checkUserCredentials(IOAuth2Client $client, $username, $password)
    {
        if (!$client instanceof ClientInterface) {
            throw new \InvalidArgumentException('Client has to implement the ClientInterface');
        }

        try {
            $user = $this->userProvider->loadUserByUsername($username);
        } catch (AuthenticationException $e) {
            return false;
        }

        if (null !== $user) {
            $encoder = $this->encoderFactory->getEncoder($user);
            
            if ($encoder->isPasswordValid($user->getPassword(), $password, $user->getSalt())) {
                return array(
                    'data' => $user,
                );
            }
        }

        return false;
    }
```

suggested code:
```
   //use Symfony\Component\Ldap\Exception\ConnectionException;
   //use Symfony\Component\Ldap\LdapInterface;
   //use Symfony\Component\Ldap\Ldap;
    public function checkUserCredentials(IOAuth2Client $client, $username, $password)
    {
        if (!$client instanceof ClientInterface) {
            throw new \InvalidArgumentException('Client has to implement the ClientInterface');
        }

        try {
            $user = $this->userProvider->loadUserByUsername($username);
        } catch (AuthenticationException $e) {
            return false;
        }

        if (null !== $user) {

			try {
				$ldap = Ldap::create('ext_ldap', ['connection_string' => 'ldap://edsldap.mydomain.com:389']);
				$ldapUsername = $ldap->escape($username, '', LdapInterface::ESCAPE_DN);
				$ldap->bind('ou=users,o=mydomain.com', '');
				$query = $ldap->query('ou=users,o=mydomain.com', sprintf('(|(uid=%1$s)(mail=%1$s))', $ldapUsername));
				$result = $query->execute();
				if (1 !== $result->count()) {
					return false;
				}
				$dn = $result[0]->getDn();
				$ldap->bind($dn, $password);
				return array(
					'data' => $user,
				);
			} catch (ConnectionException $e) {
				return false;
			}
        }

        return false;
    }
```

Please suggest what is the best way how to extend OAuthStorage class - i.e. to **inject LDAP service including its configurations** and how to **change the checkUserCredentials method** properly

Why? Our users are stored in LDAP (username and password) and authentication is done there. In database, there is only table of users (username) without passwords. Therefore needed flow is:

**OAuth password credentials request -> FOSUserBundle User-In-DB-check -> LDAP Username-Password-check ->return access_token**

I am newbie with Symfony and after few days of exploration, I still do not know how to approach this combined authentication properly. 
Thx

**Comment by kapcus** [comment]
I found example config file and based on it I have learned that I can extend Storage which resolved my problem (see below). But still I am not sure if I had put the LDAP logic into correct place - for example if "chain provider" or something similar wouldn't be better, who knows. Also FOSUserBundle is not necessary for me, I will try to eliminate it later as well as better configuration/parameter structure - please be aware of this in case you will reuse my code.

app/config/packages/fos_oauth_user.yml
```
fos_oauth_server:
  db_driver: orm
  client_class:        App\Entity\Client
  access_token_class:  App\Entity\AccessToken
  refresh_token_class: App\Entity\RefreshToken
  auth_code_class:     App\Entity\AuthCode
  service:
    storage: App\Security\OAuthStorage
    options:
      access_token_lifetime: 28800
  template:
    engine: twig
```

app/config/services.yaml
```
parameters:
    locale: 'en'
    ldap.dn: 'ou=users,o=xxxx.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.ldap:
        class: Symfony\Component\Ldap\Ldap
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
        -   host: edsldap.xxxxx.com
            port: 389
            #encryption: tls
            options:
                protocol_version: 3
                referrals: false
    App\Security\OAuthStorage:
        arguments: ['@fos_oauth_server.client_manager.default', '@fos_oauth_server.access_token_manager.default', '@fos_oauth_server.refresh_token_manager.default', '@fos_oauth_server.auth_code_manager.default', '@app.ldap', '%ldap.dn%', '@fos_user.user_provider.username_email']
```
app/config/packages/security.yaml
```
security:

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value
            provider: app_user_provider

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

```

app/src/Security/OAuthStorage.php
```
<?php
namespace App\Security;


use FOS\OAuthServerBundle\Storage\OAuthStorage as BaseOAuthStorage;
use FOS\OAuthServerBundle\Model\ClientInterface;
use FOS\OAuthServerBundle\Model\ClientManagerInterface;
use FOS\OAuthServerBundle\Model\AccessTokenManagerInterface;
use FOS\OAuthServerBundle\Model\RefreshTokenManagerInterface;
use FOS\OAuthServerBundle\Model\AuthCodeManagerInterface;
use OAuth2\Model\IOAuth2Client;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;
use Symfony\Component\Ldap\Exception\ConnectionException;
use Symfony\Component\Ldap\LdapInterface;


class OAuthStorage extends BaseOAuthStorage {
	/**
	 * @var LdapInterface
	 */
	protected $ldap;

	/**
	 * @var string
	 */
	protected $ldapDn;

	/**
	 * @param ClientManagerInterface $clientManager
	 * @param AccessTokenManagerInterface $accessTokenManager
	 * @param RefreshTokenManagerInterface $refreshTokenManager
	 * @param AuthCodeManagerInterface $authCodeManager
	 * @param \Symfony\Component\Ldap\LdapInterface $ldap
	 * @param string $ldapDn
	 * @param null|UserProviderInterface $userProvider
	 * @param null|EncoderFactoryInterface $encoderFactory
	 */
	public function __construct(ClientManagerInterface $clientManager, AccessTokenManagerInterface $accessTokenManager,
		RefreshTokenManagerInterface $refreshTokenManager, AuthCodeManagerInterface $authCodeManager, LdapInterface $ldap, string $ldapDn,
		UserProviderInterface $userProvider = null, EncoderFactoryInterface $encoderFactory = null)
	{
		$this->ldap = $ldap;
		$this->ldapDn = $ldapDn;

		parent::__construct($clientManager, $accessTokenManager, $refreshTokenManager, $authCodeManager, $userProvider, $encoderFactory);

	}

	public function checkUserCredentials(IOAuth2Client $client, $username, $password)
	{
		if (!$client instanceof ClientInterface) {
			throw new \InvalidArgumentException('Client has to implement the ClientInterface');
		}

		try {
			$user = $this->userProvider->loadUserByUsername($username);
		} catch (AuthenticationException $e) {
			return false;
		}

		if (null !== $user) {

			try {
				$ldapUsername = $this->ldap->escape($username, '', LdapInterface::ESCAPE_DN);
				$this->ldap->bind($this->ldapDn, '');
				$query = $this->ldap->query($this->ldapDn, sprintf('(|(uid=%1$s)(mail=%1$s))', $ldapUsername));
				$result = $query->execute();
				if (1 !== $result->count()) {
					return false;
				}
				$dn = $result[0]->getDn();
				$this->ldap->bind($dn, $password);
				return array(
					'data' => $user,
				);
			} catch (ConnectionException $e) {
				return false;
			}
		}

		return false;
	}
}
```
