### ISSUE TITLE
The mapping file Client.mongodb.xml is invalid

### ISSUE THREAD

**Issue by Evertt** [FriendsOfSymfony/FOSOAuthServerBundle#633]
When installing this package (at version dev-master) I get.

```
!!  In MappingException.php line 236:
!!                                                                                 
!!    The mapping file /Users/evert/Sites/mei-api/vendor/friendsofsymfony/oauth-s  
!!    erver-bundle/Resources/config/doctrine/Client.mongodb.xml is invalid:        
!!    Line 8:0: Element '{http://doctrine-project.org/schemas/odm/doctrine-mongo-  
!!    mapping}field', attribute 'fieldName': The attribute 'fieldName' is not all  
!!    owed.                                                                        
!!                                                                                 
!!    Line 9:0: Element '{http://doctrine-project.org/schemas/odm/doctrine-mongo-  
!!    mapping}field', attribute 'fieldName': The attribute 'fieldName' is not all  
!!    owed.                                                                        
!!                                                                                 
!!    Line 10:0: Element '{http://doctrine-project.org/schemas/odm/doctrine-mongo  
!!    -mapping}field', attribute 'fieldName': The attribute 'fieldName' is not al  
!!    lowed.                                                                       
!!                                                                                 
!!    Line 11:0: Element '{http://doctrine-project.org/schemas/odm/doctrine-mongo  
!!    -mapping}field', attribute 'fieldName': The attribute 'fieldName' is not al  
!!    lowed.                                                                       
!!                                                                                 
```

I checked the file `Client.mongodb.xml` and indeed it says that the attribute `fieldName` should actually be called `field-name`. I was hoping that I could just ignore this error by not using mongodb, but orm instead.

```yaml
# /config/packages/fos_auth_server.yaml

fos_oauth_server:
  db_driver: orm
  client_class: App\Entity\OAuth2\Client
  access_token_class: App\Entity\OAuth2\AccessToken
  refresh_token_class: App\Entity\OAuth2\RefreshToken
  auth_code_class: App\Entity\OAuth2\AuthCode
  service:
    user_provider: App\Provider\UserProvider

```

But that doesn't seem to make a difference. What do I do?
