### ISSUE TITLE
Manage authorized scopes with a service

### ISSUE THREAD

**Issue by Spomky** [FriendsOfSymfony/FOSOAuthServerBundle#90]
Authorized scopes can be defined in config.yml:

```
fos_oauth_server:
    service:
        options:
            supported_scopes: scope1 scope2 …
```

Is it possible to manage them with a custom service?
For examble:

```
fos_oauth_server:
    service:
        options:
            supported_scopes:
                id: my_authorized_scopes_service
```

My aim is to let bundles define the scopes they need.
my_authorized_scopes_service will lists all available scopes provided by bundles.
